"""
VLM-as-Judge evaluation framework for automated scientific figure generation.

Uses the Anthropic Claude API to evaluate generated SVG scientific figures
against source text and optional ground truth annotations. Supports single
evaluation, blind A/B comparison, and batch evaluation with aggregated statistics.
"""

from __future__ import annotations

import json
import math
import random
import re
import sys
import time
import traceback
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Any, Optional, Union

# Anthropic SDK import – gracefully degrade if not installed
try:
    import anthropic
    from anthropic import Anthropic
except ImportError:
    anthropic = None  # type: ignore[assignment]
    Anthropic = None


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MAX_SVG_LENGTH: int = 48_000  # characters – keep prompts within context window
MAX_RETRIES: int = 3
RETRY_DELAY_SECONDS: float = 2.0
JITTER_SECONDS: float = 1.0

SCORE_DIMENSIONS: list[str] = [
    "structure_correctness",
    "text_accuracy",
    "visual_clarity",
    "scientific_faithfulness",
    "overall_quality",
    "editability",
]

SCORE_DIMENSIONS_CN: dict[str, str] = {
    "structure_correctness": "结构正确性",
    "text_accuracy": "文字准确性",
    "visual_clarity": "视觉清晰度",
    "scientific_faithfulness": "科学忠实度",
    "overall_quality": "整体质量",
    "editability": "可编辑性",
}

SEVERITY_LEVELS: tuple[str, ...] = ("high", "medium", "low")

# System prompt for the evaluator – instructs Claude to act as an expert judge
SYSTEM_PROMPT_SINGLE: str = """\
You are an expert evaluator of scientific figures generated from academic paper \
text descriptions. Your task is to carefully examine an SVG figure generated by \
an automated system and score it across multiple dimensions.

The source text is an excerpt from a scientific paper describing the system, \
method, or workflow that the figure is supposed to depict.

You will receive:
1. The source text from the paper.
2. The generated SVG content (as raw XML text).
3. (Optionally) Ground truth annotations listing expected entities and relationships.

Examine the SVG in detail:
- Parse its structure: identify all <text> labels, <rect>/<circle>/<path> nodes, \
<line>/<path> edges, <g> groups, and <defs> definitions.
- Cross-reference every labeled entity against the source text.
- Check arrow directions, connection correctness, and hierarchical layout.
- Look for visual issues: overlapping elements, poor spacing, unreadable text, \
truncated labels, color misuse.
- Assess scientific accuracy: do the depicted components, flows, and relationships \
match what the paper describes?

Scoring guidelines (0 = worst, 10 = perfect):
- **structure_correctness**: Are all expected entities present? Are connections \
between them correct in direction and topology? No phantom entities or missing links.
- **text_accuracy**: Are all labels spelled correctly? No typos or garbled text? \
Do labels match the terminology used in the source text?
- **visual_clarity**: Is the layout clean and well-organized? Are elements properly \
spaced with no overlaps? Is the visual hierarchy logical? Are fonts readable?
- **scientific_faithfulness**: Does the figure correctly represent the scientific \
content described in the text? No misrepresented concepts or incorrect flows.
- **overall_quality**: Holistic judgment considering all factors together.
- **editability**: Is the SVG well-structured for manual editing? Are elements \
properly grouped with meaningful IDs? Are styles applied cleanly? Can a human \
easily modify this figure?

Issues: Identify specific problems. Each issue must have:
- severity: "high" | "medium" | "low"
- category: e.g. "missing_entity", "wrong_connection", "spelling_error", \
"overlap", "layout", "scientific_error", "svg_structure", "other"
- description: concise explanation in English

Output ONLY a valid JSON object (no markdown fences, no extra text) with this shape:
{
  "structure_correctness": <int 0-10>,
  "text_accuracy": <int 0-10>,
  "visual_clarity": <int 0-10>,
  "scientific_faithfulness": <int 0-10>,
  "overall_quality": <int 0-10>,
  "editability": <int 0-10>,
  "issues": [
    {"severity": "high|medium|low", "category": "...", "description": "..."}
  ],
  "summary": "Chinese summary of the evaluation"
}"""

SYSTEM_PROMPT_COMPARISON: str = """\
You are an expert evaluator of scientific figures generated from academic paper \
text descriptions. You will compare TWO generated figures (labeled "Figure A" and \
"Figure B") and determine which one better represents the source text.

You will receive:
1. The source text from the paper.
2. Two SVG figures, labeled Figure A and Figure B.
3. (Optionally) Ground truth annotations.

The figures were generated by different methods from the same source text. \
Your task is to do a blind, objective comparison.

Evaluate each figure independently on the standard dimensions, then compare:

Scoring dimensions (each 0-10):
- structure_correctness, text_accuracy, visual_clarity, scientific_faithfulness, \
overall_quality, editability

After scoring both, declare a winner ("A", "B", or "tie") based on which figure \
is better overall. If scores are very close (within 1 point on overall_quality), \
prefer "tie".

Also list which specific dimensions Figure A wins on and which Figure B wins on.

Output ONLY a valid JSON object (no markdown fences, no extra text) with this shape:
{
  "scores": {
    "A": {
      "structure_correctness": <int>,
      "text_accuracy": <int>,
      "visual_clarity": <int>,
      "scientific_faithfulness": <int>,
      "overall_quality": <int>,
      "editability": <int>,
      "issues": [...]
    },
    "B": { ... same shape ... }
  },
  "winner": "A" | "B" | "tie",
  "a_better_than_b_on": ["dimension_name", ...],
  "b_better_than_a_on": ["dimension_name", ...],
  "comparison_notes": "Chinese comparison summary"
}"""


# ---------------------------------------------------------------------------
# Helper utilities
# ---------------------------------------------------------------------------

def _truncate_svg(svg: str, max_len: int = MAX_SVG_LENGTH) -> str:
    """Truncate SVG content to fit within context limits while preserving structure.

    If truncation is needed, we keep the beginning (which contains <svg> attributes,
    <defs>, and initial elements) and the end (closing tags), removing the middle.
    """
    if len(svg) <= max_len:
        return svg

    # Keep 70% from the start, 20% from the end, and insert a truncation notice
    head_ratio = 0.70
    tail_ratio = 0.20
    head_len = int(max_len * head_ratio)
    tail_len = int(max_len * tail_ratio)
    half_gap = (max_len - head_len - tail_len) // 2

    head = svg[:head_len]
    tail = svg[-tail_len:]

    notice = (
        f"\n<!-- [{half_gap} characters omitted for length; "
        f"original SVG was {len(svg)} chars] -->\n"
    )

    return head + notice + tail


def _extract_json_from_response(text: str) -> str:
    """Extract a JSON object from a response that may contain markdown fences
    or surrounding text.

    Tries:
    1. Direct JSON parse of the full text.
    2. Extract content between ```json ... ``` fences.
    3. Extract content between { and } braces (greedy outermost).
    """
    text = text.strip()

    # Try direct parse
    try:
        json.loads(text)
        return text
    except json.JSONDecodeError:
        pass

    # Try fenced code block
    fence_patterns = [
        r"```json\s*([\s\S]*?)\s*```",
        r"```\s*([\s\S]*?)\s*```",
    ]
    for pat in fence_patterns:
        m = re.search(pat, text)
        if m:
            candidate = m.group(1).strip()
            try:
                json.loads(candidate)
                return candidate
            except json.JSONDecodeError:
                continue

    # Try balanced braces extraction
    # Find the first { and the matching last }
    first_brace = text.find("{")
    if first_brace >= 0:
        depth = 0
        last_brace = first_brace
        for i, ch in enumerate(text[first_brace:], start=first_brace):
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    last_brace = i
                    break
        if last_brace > first_brace:
            candidate = text[first_brace : last_brace + 1]
            try:
                json.loads(candidate)
                return candidate
            except json.JSONDecodeError:
                pass

    return text


def _validate_scores(result: dict[str, Any], dims: tuple[str, ...]) -> dict[str, Any]:
    """Ensure all score dimensions are present, integers, and in range [0, 10]."""
    for dim in dims:
        if dim not in result:
            result[dim] = 0
        else:
            try:
                val = int(result[dim])
                result[dim] = max(0, min(10, val))
            except (ValueError, TypeError):
                result[dim] = 0

    # Ensure issues is a list
    if "issues" not in result or not isinstance(result["issues"], list):
        result["issues"] = []

    # Clean issues
    cleaned_issues = []
    for issue in result["issues"]:
        if not isinstance(issue, dict):
            continue
        cleaned_issues.append({
            "severity": issue.get("severity", "medium")
            if issue.get("severity") in SEVERITY_LEVELS
            else "medium",
            "category": issue.get("category", "other"),
            "description": issue.get("description", ""),
        })
    result["issues"] = cleaned_issues

    if "summary" not in result:
        result["summary"] = ""

    return result


def _compute_stats(values: list[float]) -> dict[str, float]:
    """Compute mean and standard deviation for a list of numeric values."""
    n = len(values)
    if n == 0:
        return {"mean": 0.0, "std": 0.0, "min": 0.0, "max": 0.0, "count": 0}

    mean = sum(values) / n
    variance = sum((x - mean) ** 2 for x in values) / n
    std = math.sqrt(variance)
    return {
        "mean": round(mean, 2),
        "std": round(std, 2),
        "min": round(min(values), 2),
        "max": round(max(values), 2),
        "count": n,
    }


# ---------------------------------------------------------------------------
# Anthropic API client wrapper
# ---------------------------------------------------------------------------

class _ClaudeClient:
    """Thin wrapper around the Anthropic Python SDK with retry logic."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: str = "claude-sonnet-4-6",
        max_retries: int = MAX_RETRIES,
    ):
        if anthropic is None or Anthropic is None:
            raise ImportError(
                "The 'anthropic' package is required for FigureEvaluator. "
                "Install it with: pip install anthropic"
            )

        self._model = model
        self._max_retries = max_retries

        # Resolve API key: explicit arg > env var > .netrc / default
        resolved_key = api_key
        if resolved_key is None:
            # Let the SDK handle its default resolution (env, config, etc.)
            resolved_key = None

        self._client = Anthropic(api_key=resolved_key)

    def send_message(
        self,
        system_prompt: str,
        user_content: str,
        temperature: float = 0.1,
        max_tokens: int = 4096,
    ) -> str:
        """Send a message to Claude and return the text response.

        Implements automatic retry on transient failures and JSON parse errors
        during the calling code's subsequent processing.
        """
        last_error: Optional[Exception] = None

        for attempt in range(1, self._max_retries + 1):
            try:
                message = self._client.messages.create(
                    model=self._model,
                    max_tokens=max_tokens,
                    temperature=temperature,
                    system=system_prompt,
                    messages=[
                        {"role": "user", "content": user_content},
                    ],
                )

                # Extract text from the first text block
                text_blocks = [
                    block.text
                    for block in message.content
                    if getattr(block, "type", None) == "text"
                ]
                if not text_blocks:
                    raise RuntimeError(
                        f"No text content in response: {message.content}"
                    )
                return "".join(text_blocks)

            except (anthropic.APIError, anthropic.APIConnectionError,
                    anthropic.RateLimitError, anthropic.APITimeoutError) as exc:
                last_error = exc
                if attempt < self._max_retries:
                    wait = RETRY_DELAY_SECONDS * attempt + random.uniform(
                        0, JITTER_SECONDS
                    )
                    time.sleep(wait)
                    continue
                raise RuntimeError(
                    f"Claude API call failed after {self._max_retries} retries: {exc}"
                ) from exc

            except anthropic.BadRequestError as exc:
                # Do not retry on bad requests (e.g. content filter, prompt too long)
                raise RuntimeError(
                    f"Claude API rejected the request: {exc}"
                ) from exc

        # Should not be reached, but guard against empty retry loop
        raise RuntimeError(
            f"Claude API call failed: {last_error}"
        )


# ---------------------------------------------------------------------------
# FigureEvaluator
# ---------------------------------------------------------------------------

class FigureEvaluator:
    """Evaluates scientific figures using VLM-as-Judge with the Claude API.

    Usage:
        evaluator = FigureEvaluator(api_key="...")
        result = evaluator.evaluate_single(text, svg, ground_truth)
        comp = evaluator.evaluate_comparison(text, svg_a, svg_b)
        batch = evaluator.batch_evaluate(test_cases, results)
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: str = "claude-sonnet-4-6",
    ):
        """Initialize the evaluator with an Anthropic API key.

        Args:
            api_key: Anthropic API key. If None, uses the ANTHROPIC_API_KEY
                environment variable or the SDK default resolution.
            model: Claude model identifier. Default: "claude-sonnet-4-6".
        """
        self._client = _ClaudeClient(api_key=api_key, model=model)
        self._model = model

    # ------------------------------------------------------------------
    # Single evaluation
    # ------------------------------------------------------------------

    def evaluate_single(
        self,
        text: str,
        svg: str,
        ground_truth: Optional[dict] = None,
    ) -> dict[str, Any]:
        """Evaluate one generated figure against the source text.

        Args:
            text: The source paper excerpt describing the system/method.
            svg: The generated SVG figure content as a string.
            ground_truth: Optional dict with "key_entities", "key_relationships",
                and "description" fields for reference.

        Returns:
            A dict with scores (0-10), issues list, and a Chinese summary.
            See module docstring for full shape.
        """
        truncated_svg = _truncate_svg(svg)

        # Build the user prompt
        parts: list[str] = []
        parts.append("=== SOURCE TEXT ===")
        parts.append(text)
        parts.append("")
        parts.append("=== GENERATED SVG FIGURE ===")
        parts.append(truncated_svg)

        if ground_truth:
            parts.append("")
            parts.append("=== GROUND TRUTH (for reference) ===")
            parts.append(json.dumps(ground_truth, ensure_ascii=False, indent=2))

        parts.append("")
        parts.append(
            "Please evaluate the generated figure against the source text. "
            "Provide your response as a single JSON object with scores, issues, "
            "and a Chinese summary."
        )

        user_content = "\n".join(parts)

        raw_response = self._retry_json_call(
            system_prompt=SYSTEM_PROMPT_SINGLE,
            user_content=user_content,
        )

        result = self._parse_json_response(raw_response, "evaluate_single")
        result = _validate_scores(result, tuple(SCORE_DIMENSIONS))

        return result

    # ------------------------------------------------------------------
    # Comparison evaluation
    # ------------------------------------------------------------------

    def evaluate_comparison(
        self,
        text: str,
        svg_a: str,
        svg_b: str,
        ground_truth: Optional[dict] = None,
    ) -> dict[str, Any]:
        """Blind comparison of two generated figures.

        The figures are randomly assigned as "Figure A" and "Figure B"
        internally to ensure blind evaluation. The returned result
        references the randomized labels, and the mapping is included
        so the caller can determine which original figure won.

        Args:
            text: The source paper excerpt.
            svg_a: First generated SVG.
            svg_b: Second generated SVG.
            ground_truth: Optional ground truth annotations.

        Returns:
            A dict with:
            - winner: "A" or "B" or "tie" (referring to randomized labels)
            - scores: dict with "A" and "B" keys, each containing score dicts
            - comparison_notes: Chinese comparison summary
            - a_better_than_b_on: dimensions A won
            - b_better_than_a_on: dimensions B won
            - randomized_mapping: {"A": "svg_a" or "svg_b", "B": the other}
        """
        # Randomly assign which SVG gets which label
        swap = random.choice([False, True])
        if swap:
            figure_a_content = svg_b
            figure_b_content = svg_a
            mapping = {"A": "svg_b", "B": "svg_a"}
        else:
            figure_a_content = svg_a
            figure_b_content = svg_b
            mapping = {"A": "svg_a", "B": "svg_b"}

        truncated_a = _truncate_svg(figure_a_content)
        truncated_b = _truncate_svg(figure_b_content)

        parts: list[str] = []
        parts.append("=== SOURCE TEXT ===")
        parts.append(text)
        parts.append("")
        parts.append("=== FIGURE A ===")
        parts.append(truncated_a)
        parts.append("")
        parts.append("=== FIGURE B ===")
        parts.append(truncated_b)

        if ground_truth:
            parts.append("")
            parts.append("=== GROUND TRUTH (for reference) ===")
            parts.append(json.dumps(ground_truth, ensure_ascii=False, indent=2))

        parts.append("")
        parts.append(
            "Please evaluate both figures independently and compare them. "
            "Provide your response as a single JSON object."
        )

        user_content = "\n".join(parts)

        raw_response = self._retry_json_call(
            system_prompt=SYSTEM_PROMPT_COMPARISON,
            user_content=user_content,
        )

        result = self._parse_json_response(raw_response, "evaluate_comparison")

        # Validate the nested scores
        if "scores" not in result or not isinstance(result["scores"], dict):
            result["scores"] = {"A": {}, "B": {}}

        for label in ("A", "B"):
            if label not in result["scores"]:
                result["scores"][label] = {}
            result["scores"][label] = _validate_scores(
                result["scores"][label],
                tuple(SCORE_DIMENSIONS),
            )

        # Ensure required top-level keys
        result.setdefault("winner", "tie")
        result.setdefault("a_better_than_b_on", [])
        result.setdefault("b_better_than_a_on", [])
        result.setdefault("comparison_notes", "")
        result["randomized_mapping"] = mapping

        return result

    # ------------------------------------------------------------------
    # Batch evaluation
    # ------------------------------------------------------------------

    def batch_evaluate(
        self,
        test_cases: list[dict],
        results: dict[str, dict],
    ) -> dict[str, Any]:
        """Evaluate all test cases and aggregate metrics.

        Args:
            test_cases: List of test case dicts (each with "id", "text",
                "figure_type", "ground_truth").
            results: Dict mapping test_case_id to {"svg": str, "method": str}.
                Each test_case_id can map to a list of result dicts if multiple
                methods generated figures for the same test case.

        Returns:
            Aggregated metrics dict:
            {
                "per_case": {tc_id: {evaluation dict}},
                "aggregate": {
                    "by_dimension": {dim: stats_dict},
                    "by_type": {figure_type: {dim: stats_dict}},
                    "by_method": {method: {dim: stats_dict}},
                },
                "summary": "Chinese batch evaluation summary",
            }
        """
        per_case: dict[str, Any] = {}
        all_scores: dict[str, list[float]] = defaultdict(list)
        by_type: dict[str, dict[str, list[float]]] = defaultdict(
            lambda: defaultdict(list)
        )
        by_method: dict[str, dict[str, list[float]]] = defaultdict(
            lambda: defaultdict(list)
        )

        # Build lookup for ground truth
        tc_map: dict[str, dict] = {tc["id"]: tc for tc in test_cases}

        for tc_id, result_entry in results.items():
            tc = tc_map.get(tc_id)
            if tc is None:
                per_case[tc_id] = {
                    "error": f"Unknown test case ID: {tc_id}",
                }
                continue

            svg = result_entry.get("svg", "")
            method = result_entry.get("method", "unknown")

            try:
                evaluation = self.evaluate_single(
                    text=tc["text"],
                    svg=svg,
                    ground_truth=tc.get("ground_truth"),
                )
            except Exception as exc:
                evaluation = {
                    "error": str(exc),
                    "traceback": traceback.format_exc(),
                }
                for dim in SCORE_DIMENSIONS:
                    evaluation[dim] = 0

            evaluation["method"] = method
            evaluation["figure_type"] = tc.get("figure_type", "unknown")
            per_case[tc_id] = evaluation

            # Collect scores for aggregation (skip errors)
            if "error" not in evaluation:
                for dim in SCORE_DIMENSIONS:
                    score = evaluation.get(dim, 0)
                    all_scores[dim].append(score)
                    by_type[tc.get("figure_type", "unknown")][dim].append(score)
                    by_method[method][dim].append(score)

        # Compute aggregate statistics
        aggregate: dict[str, Any] = {
            "by_dimension": {
                dim: _compute_stats(all_scores.get(dim, []))
                for dim in SCORE_DIMENSIONS
            },
            "by_type": {
                ftype: {
                    dim: _compute_stats(scores.get(dim, []))
                    for dim in SCORE_DIMENSIONS
                }
                for ftype, scores in by_type.items()
            },
            "by_method": {
                method: {
                    dim: _compute_stats(scores.get(dim, []))
                    for dim in SCORE_DIMENSIONS
                }
                for method, scores in by_method.items()
            },
        }

        # Generate a summary in Chinese
        summary_parts: list[str] = []
        summary_parts.append(f"批量评估完成，共 {len(results)} 个测试用例。")
        for dim in SCORE_DIMENSIONS:
            stats = aggregate["by_dimension"][dim]
            cn_name = SCORE_DIMENSIONS_CN.get(dim, dim)
            summary_parts.append(
                f"{cn_name}: 均值={stats['mean']}, 标准差={stats['std']}, "
                f"范围=[{stats['min']}, {stats['max']}], 样本数={stats['count']}"
            )

        if len(by_method) > 1:
            summary_parts.append(
                f"共 {len(by_method)} 种方法参与评估: {', '.join(sorted(by_method.keys()))}。"
            )

        return {
            "per_case": per_case,
            "aggregate": aggregate,
            "summary": "\n".join(summary_parts),
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _retry_json_call(
        self,
        system_prompt: str,
        user_content: str,
    ) -> str:
        """Call Claude with retry specifically for JSON parse failures.

        If the response is not valid JSON, we retry with an additional
        instruction to output only valid JSON.
        """
        last_response: Optional[str] = None
        last_error: Optional[Exception] = None

        for attempt in range(1, MAX_RETRIES + 1):
            try:
                response = self._client.send_message(
                    system_prompt=system_prompt,
                    user_content=user_content,
                    temperature=0.1,
                    max_tokens=4096,
                )
            except Exception as exc:
                last_error = exc
                if attempt < MAX_RETRIES:
                    wait = RETRY_DELAY_SECONDS * attempt + random.uniform(
                        0, JITTER_SECONDS
                    )
                    time.sleep(wait)
                    continue
                raise RuntimeError(
                    f"Claude API call failed after {MAX_RETRIES} retries: {exc}"
                ) from exc

            last_response = response

            # Try to parse as JSON
            extracted = _extract_json_from_response(response)
            try:
                json.loads(extracted)
                return extracted  # Valid JSON – we are done
            except json.JSONDecodeError as exc:
                last_error = exc
                if attempt < MAX_RETRIES:
                    # Add a stern reminder to the prompt for the retry
                    user_content = (
                        user_content
                        + "\n\n[SYSTEM NOTE: Your previous response was NOT valid JSON. "
                        + f"Error: {exc}. "
                        + "You MUST output ONLY a single valid JSON object. "
                        + "No markdown fences, no surrounding text, no trailing commas, "
                        + "no comments. ONLY valid JSON.]"
                    )
                    wait = RETRY_DELAY_SECONDS * attempt + random.uniform(
                        0, JITTER_SECONDS
                    )
                    time.sleep(wait)
                    continue

        # All retries exhausted
        raise RuntimeError(
            f"Failed to get valid JSON after {MAX_RETRIES} retries. "
            f"Last JSON error: {last_error}. "
            f"Last raw response (first 500 chars): {str(last_response)[:500]}"
        )

    @staticmethod
    def _parse_json_response(raw: str, method_name: str) -> dict[str, Any]:
        """Parse the JSON response, with a fallback for partial extraction."""
        extracted = _extract_json_from_response(raw)
        try:
            result = json.loads(extracted)
            if not isinstance(result, dict):
                raise ValueError(f"Expected JSON object, got {type(result).__name__}")
            return result
        except (json.JSONDecodeError, ValueError) as exc:
            raise RuntimeError(
                f"{method_name}: Failed to parse JSON response. "
                f"Error: {exc}. "
                f"Raw (first 800 chars): {raw[:800]}"
            ) from exc
